### ISSUE TITLE
Example no longer works with latest versions

### ISSUE THREAD

**Issue by ifandelse** [mj1618/serverless-offline-sns-example#3]
When I tried updating the example deps to their latest versions (5.12.1 for serverless-offline and 0.68.0 for serverless-offline-sns), the example no longer worked. Running w/debug set to true, you can still see things happening in the background, but the `pong` handler never executes.

Could you provide some input on what versions should work together? Thanks!

**Comment by crucialfelix** [comment]
```sh
serverless-offline-sns-example ❯ sls offline
Serverless: Starting Offline: dev/us-east-1.

Serverless: Routes for pong:
Serverless: (none)

Serverless: Routes for ping:
Serverless: GET /ping

Serverless: Offline listening on http://localhost:3000

Serverless: GET /ping (λ: ping)
Serverless: The first request might take a few extra seconds
ping
Serverless: [200] {"response":"return from lambda ping"}
```

**Comment by crucialfelix** [comment]
> serverless-offline-sns supports http, https, and sqs subscriptions. email, email-json, sms, application, and **lambda** protocols are not supported at this time.

https://github.com/mj1618/serverless-offline-sns/blob/master/README.md#subscribing

It's generally better for SNS to have (multiple) SQS queues subscribing to it. That's more work to set up in Resources though.

**Comment by ifandelse** [comment]
@crucialfelix perhaps I'm misunderstanding what should happen here, but the pong lambda has two console.log statements in it - and those don't appear. So I see the same output you posted above, but I also expected to see the additional console.log statements from the pong lambda as it executed.

**Comment by crucialfelix** [comment]
Exactly, that's the problem. It does not pong.

To clarify, this is because serverless-offline-sns does not support lambda events.  I don't think this example could ever have worked.  

You can connect an SNS topic to a lambda in production. However best practice is to connect an SQS queue to read from the SNS topic. Each of the SQS events then gets handled by lambda handlers (in parallel). Then you should also set up DLQ in case the lambda is down etc. etc.

I have realized that it's actually cheaper to just deploy to a staging environment. Then you get more tooling to trace problems.  Otherwise we spend a lot of time trying to mock or fake the live setup.

**Comment by ifandelse** [comment]
Thanks @crucialfelix - I'm new to AWS since August, and I'm coming to the same conclusion (cheaper to deploy to a staging env).
